name = "react-hono-todo"
compatibility_date = "2023-02-05"
# pages_build_output_dir = "pages"

[[d1_databases]]
binding = "DB"
database_name = "todo-db"
database_id = "6cf810c9-d67c-40e0-8f6b-8748902155e8"
